# @package _global_

defaults:
  - classification_base


dataset:
  name: swissprot
  simple_cls:
    _target_: datasets.prot.swissprot.SPSimpleDataset

  set_cls:
    _target_: datasets.prot.swissprot.SPSetDataset

backbone:
  _target_: backbones.resnet.ResNet
  block: backbones.blocks.SimpleBlock
  list_of_num_layers: [1, 1, 1, 1]
  layer_dim: [64, 128, 256, 512]

train_classes: 7195

n_way: 5
n_shot: 5
n_query: 15

